apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap

# LOGO ABAIXO DEFININDO VARIAVEIS DE AMBIENTE PARA O MYSQL, DEFINIDO VARIAVEL DE AMBIENTE NO ARQUIVO db-configmap.yaml
      #   - name: "MYSQL_ROOT_PASSWORD"   
       #    value: "1234q" #SENHA ROOT

        # - name: "MYSQL_DATABASE"   
        #   value: "EMPRESA" #NOME DO DATABASE 

        # - name: "MY_SQL_PASSWORD"   
         #  value: "q123"   #SENHA DO DATABASE   